// login action
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// register action
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_FINALLY = "USER_REGISTER_FINALLY";

// logout action
export const USER_LOGOUT = "USER_LOGOUT";

// cart action
export const ADD_CART__REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const GET_CART_DETAIL = "GET_CART_DETAIL";
export const UPDATE_CART = "UPDATE_CART";

// comment action
export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMET_FAIL";
